name: ingo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  page_transition: ^2.1.0
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/svg/
    - assets/images/svg/onBoarding/
    - assets/images/svg/onBoarding/background/
    - assets/images/png/
    - assets/images/png/onBoarding/
    - assets/images/lottie/onBoarding/
    - assets/i18n/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200 
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300 
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600 
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900 
        
